### ISSUE TITLE
缺少依赖com.kaciras.blog:infra:jar:1.1.3 

### ISSUE THREAD

**Issue by sdugao** [kaciras-blog/content-server#1]
Could not resolve dependencies for project com.kaciras.blog:content-server:jar:1.0.0: Failure to find com.kaciras.blog:infra:jar:1.1.3 in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of alimaven has elapsed or updates are forced

**Comment by Kaciras** [comment]
额……已解决。

很抱歉因为设置错误，GitHub 没给我发邮件，未能及时看到。
